version: '3'

services:
  eventsub:
    build:
      context: ./Golang
      dockerfile: ./Dockerfile
      target: eventsub
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json

      - type: bind
        source: ./Golang/db/
        target: /app/db/
    network_mode: host

  firehose:
    build:
      context: ./Golang
      dockerfile: ./Dockerfile
      target: firehose
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
    network_mode: host
