version: '3'

services:
  eventsub:
    build:
      context: ./Golang
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json

      - type: bind
        source: ./Golang/db/
        target: /app/db/
    # Quick access to redis and postgres
    network_mode: host
