version: '3'

services:
  eventsub:
    build:
      context: ./Golang
      dockerfile: ./EventSub/Dockerfile
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
    # Quick access to redis and postgres
    network_mode: host
